---
title: "Free and Open Source Software for Open Science"
author: "Compiled by the #psyteachr team at University of Glasgow Psychology"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Programming Experiments

- [PsychoPy](http://www.psychopy.org/) - a free, powerful alternative to Presentation™ or e-Prime™, written in Python
- [OpenSesame](https://osdoc.cogsci.nl/3.1/) - Another free experiment presentation software.  Very similar to PsychoPy, but does not work on all Macs.

## Animation / Video

- [Open Broadcasting System](https://sproject.com) - Free and open source software for video recording and live streaming
- [av package for R](https://github.com/ropensci/av#readme) - The av Package: Production Quality Video in R [(blog)](https://ropensci.org/technotes/2018/10/06/av-release/)

## Images

- [Canava](https://www.canva.com/) - for making infographics and posters
- [imagemagick](https://www.imagemagick.org/) - command-line tools for image processing
- [GNU Image Manipulation Program (GIMP)](https://www.gimp.org/) - powerful alternative to Adobe Photoshop

## Class Interaction

- [Sli.do](https://www.sli.do/) - Audience interaction software.  Free version gives 3 polls and is is very easy and intuitive to use (GDPR compliant at time of writing)
- [Padlet](https://en-gb.padlet.com/) - collaborative workspaces/notice boards.  The free version gives 12 padlets, but they can be reused (GDPR compliant at time of writing)

## Building tutorials

- [learnr](https://rstudio.github.io/learnr/) - Develop online tutorials implemented using the [shiny](https://www.rstudio.com/products/shiny/) platform for web apps
- [webex](https://github.com/psyteachr/webex/) - Develop web tutorials as standalone HTML files

## Bookdown styles for textbooks

- [#psyteachr style](https://psyteachr.github.io/book-template/) - The bookdown style used by #psyteachr, which includes HTML webex widgets
- [`msmbstyle` style](https://github.com/grimbough/msmbstyle) - A style inspired by the Tufte handout design, created by [Mike Smith](https://twitter.com/grimbough)

## Exams and coursework

- [assessr](https://github.com/psyteachr/assessr/) - Generate and assess R assignments in RMarkdown (in development)
- [flexTeaching](https://github.com/richarddmorey/flexTeaching/) - Use RStudio flexdashboards to create random stats assignments
- [generate-exam](https://github.com/ritcheym/generate-exam) - Generate a formatted exam from a CSV of questions
- [exams](http://www.r-exams.org/) - Generate exams/quizzes/tests in a variety of formats
- [markr](https://gupsych.github.io/trdair_workshop/feedback.html) - Generating exam and assessment feedback reports (in development)
